# Generated by Django 3.0.4 on 2021-01-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_timeline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'About Me', 'verbose_name_plural': 'About Me'},
        ),
        migrations.AlterModelOptions(
            name='timeline',
            options={'verbose_name': 'Timeline', 'verbose_name_plural': 'Timelines'},
        ),
        migrations.AlterField(
            model_name='timeline',
            name='date',
            field=models.DateField(),
        ),
    ]
