# Generated by Django 3.0.4 on 2021-01-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
