# Generated by Django 3.0.4 on 2021-01-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20210109_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
