# Generated by Django 3.0.4 on 2021-01-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20210109_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
