# Generated by Django 3.0.4 on 2021-01-09 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_auto_20210109_0843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expertise',
        ),
    ]
