# Generated by Django 3.0.4 on 2021-01-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_delete_expertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_file', models.ImageField(null=True, upload_to='uploads/')),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
        ),
    ]
